set hlsearch
set ts=4

set lbr

set guifont=DejaVu\ Sans\ Mono\ 9


if has("gui_gtk2")
	set lines=55
	set columns=120
else
endif


nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk
